version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: {project_name}
    command: sh /home/ubuntu/start.sh
    ports:
      - "80:80"
    volumes:
      - ./www/:/var/www:rw
    environment:
      TZ: "Europe/Prague"
      PYTHONPATH: /var/www/
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 512M
          
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./db/:/var/lib/postgresql/data/:rw
    environment:
      - POSTGRES_USER={project_name}
      - POSTGRES_PASSWORD={project_name}
      - POSTGRES_DB={project_name}

